---------------------------
--   My awesome theme    --
---------------------------

theme = {}

theme.font          = "montecarlo 10"

theme.bg_normal     = "#1a1a1a"
theme.bg_focus      = "#1a1a1a"
theme.bg_urgent     = "#1a1a1a"
theme.bg_minimize   = "#444444"

theme.fg_normal     = "#ecedee"
theme.fg_focus      = "#8c8c8c"
theme.fg_urgent     = "#65909a"
theme.fg_minimize   = "#ffffff"

theme.border_width  = "1"
theme.border_normal = "#070707"
theme.border_focus  = "#606060"
theme.border_marked = "#3ca4d8"

theme.arch_blue     = "#1793d1"

-- Display the taglist squares
theme.taglist_squares_sel   = "/usr/share/awesome/themes/default/taglist/squarefw.png"
theme.taglist_squares_unsel = "/usr/share/awesome/themes/default/taglist/squarew.png"

theme.tasklist_floating_icon = "/usr/share/awesome/themes/default/tasklist/floatingw.png"

-- Variables set for theming the menu:
theme.menu_height = "17"
theme.menu_width  = "100"
theme.menu_fg_normal = "#ecedee"
theme.menu_fg_focus =  "#65909A"
theme.menu_bg_normal = "#000000aa"
theme.menu_bg_focus  = "#000000dd"
theme.menu_border_width = "0"

--Icons
config = "~/.config/awesome/"
themedir = config .. "themes/alan/"

theme.widget_mpd   = themedir .. "icons/note.png"
theme.widget_play  = themedir .. "icons/play.png"
theme.widget_pause = themedir .. "icons/pause.png"
theme.widget_stop  = themedir .. "icons/stop.png"
theme.widget_prev  = themedir .. "icons/prev.png"
theme.widget_next  = themedir .. "icons/next.png"

-- Layout
theme.layout_tile       = themedir .. "layouts/tile.png"
theme.layout_tileleft   = themedir .. "layouts/tileleft.png"
theme.layout_tilebottom = themedir .. "layouts/tilebottom.png"
theme.layout_tiletop    = themedir .. "layouts/tiletop.png"
theme.layout_fairv      = themedir .. "layouts/fairv.png"
theme.layout_fairh      = themedir .. "layouts/fairh.png"
theme.layout_spiral     = themedir .. "layouts/spiral.png"
theme.layout_dwindle    = themedir .. "layouts/dwindle.png"
theme.layout_max        = themedir .. "layouts/max.png"
theme.layout_fullscreen = themedir .. "layouts/fullscreen.png"
theme.layout_magnifier  = themedir .. "layouts/magnifier.png"
theme.layout_floating   = themedir .. "layouts/floating.png"

-- Define the image to load
theme.titlebar_close_button_normal = "/usr/share/awesome/themes/default/titlebar/close_normal.png"
theme.titlebar_close_button_focus  = "/usr/share/awesome/themes/default/titlebar/close_focus.png"

theme.titlebar_ontop_button_normal_inactive = "/usr/share/awesome/themes/default/titlebar/ontop_normal_inactive.png"
theme.titlebar_ontop_button_focus_inactive  = "/usr/share/awesome/themes/default/titlebar/ontop_focus_inactive.png"
theme.titlebar_ontop_button_normal_active = "/usr/share/awesome/themes/default/titlebar/ontop_normal_active.png"
theme.titlebar_ontop_button_focus_active  = "/usr/share/awesome/themes/default/titlebar/ontop_focus_active.png"

theme.titlebar_sticky_button_normal_inactive = "/usr/share/awesome/themes/default/titlebar/sticky_normal_inactive.png"
theme.titlebar_sticky_button_focus_inactive  = "/usr/share/awesome/themes/default/titlebar/sticky_focus_inactive.png"
theme.titlebar_sticky_button_normal_active = "/usr/share/awesome/themes/default/titlebar/sticky_normal_active.png"
theme.titlebar_sticky_button_focus_active  = "/usr/share/awesome/themes/default/titlebar/sticky_focus_active.png"

theme.titlebar_floating_button_normal_inactive = "/usr/share/awesome/themes/default/titlebar/floating_normal_inactive.png"
theme.titlebar_floating_button_focus_inactive  = "/usr/share/awesome/themes/default/titlebar/floating_focus_inactive.png"
theme.titlebar_floating_button_normal_active = "/usr/share/awesome/themes/default/titlebar/floating_normal_active.png"
theme.titlebar_floating_button_focus_active  = "/usr/share/awesome/themes/default/titlebar/floating_focus_active.png"

theme.titlebar_maximized_button_normal_inactive = "/usr/share/awesome/themes/default/titlebar/maximized_normal_inactive.png"
theme.titlebar_maximized_button_focus_inactive  = "/usr/share/awesome/themes/default/titlebar/maximized_focus_inactive.png"
theme.titlebar_maximized_button_normal_active = "/usr/share/awesome/themes/default/titlebar/maximized_normal_active.png"
theme.titlebar_maximized_button_focus_active  = "/usr/share/awesome/themes/default/titlebar/maximized_focus_active.png"

-- You can use your own command to set your wallpaper
theme.wallpaper_cmd = { "awsetbg -r /home/alan/media/images/bg/"}

return theme
